name: Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    uses: BijanProgrammerWebsites/hub/.github/workflows/deploy-angular.yml@master
    with:
      host: slides.bijanprogrammer.com
      base-href: /storybook/
      project-name: storybook
